spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: richtev
    url: jdbc:mysql://localhost:3306/kangyong?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher